{% set name = "json" %}
{% set version = "2.3.0" %}

package:
  name: rb-{{ name|lower }}
  version: {{ version }}

source:
  url: https://rubygems.org/downloads/{{ name }}-{{ version }}.gem
  sha256: b61691fd2087ac37141b75ff4287ce2c3f17251c713e97ef73b43b4bb2e0355b

build:
  number: 0
  script:
    - gem install -N -l -V --norc --ignore-dependencies {{ name }}-{{ version }}.gem --
        --use-system-libraries  # [osx and rb25]
    {% for dir in [ '', 'ext/generator', 'ext/parser' ] %}
    - make -C {{ PREFIX }}/lib/ruby/gems/{{ ruby }}.0/gems/{{ name }}-{{ version }}/ext/{{ name }}/{{ dir }} clean
    {% endfor%}
  skip: {{ win }}

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - ruby
  run:
    - ruby

test:
  commands:
    - ruby -r {{ name }} -e 'exit 0'

about:
  home: https://rubygems.org/gems/{{ name }}
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: This is a JSON implementation as a Ruby extension in C.
  doc_url: https://www.rubydoc.info/gems/{{ name }}
  dev_url: http://flori.github.io/json/

extra:
  recipe-maintainers:
    - oblute
    - benhuff
    - sodre
