{% set name = "json" %}
{% set version = "1.8.6" %}

package:
  name: rb-{{ name|lower }}
  version: {{ version }}

source:
  url: https://rubygems.org/downloads/{{ name }}-{{ version }}.gem
  sha256: 65af27ca985f70eb0d083aab0f75712c771871222af021ce533bad77bd3bb262

build:
  number: 0
  script:
    - gem install -N -l -V --norc --ignore-dependencies {{ name }}-{{ version }}.gem
    {% for dir in [ '', 'ext/generator', 'ext/parser' ] %}
    - make -C {{ PREFIX }}/lib/ruby/gems/{{ ruby }}.0/gems/{{ name }}-{{ version }}/ext/{{ name }}/{{ dir }} clean
    {% endfor%}  
  skip: {{ win }}

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - ruby
  run:
    - ruby

test:
  commands:
    - ruby -r {{ name }} -e 'exit 0'

about:
  home: https://rubygems.org/gems/{{ name }}
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: This is a JSON implementation as a Ruby extension in C.
  doc_url: https://www.rubydoc.info/gems/{{ name }}
  dev_url: http://flori.github.io/json/

extra:
  recipe-maintainers:
    - oblute
    - benhuff
    - sodre
