travis:
  secure:
    BINSTAR_TOKEN: l9EOid68GlPwZvV73OlTnuhewJN1lAqywf7o06nmCV+YD6vWrZ64Kp6PC+q86UcbSGxx3doolaoRyBLKvsa+f+lhFkE0GdrPG5R0IOlWbowkG46Dbam2uVcS2ep5G9CGIyp7+NtIoZPHRrFC/bjmltP/1yWq4Lm9hkx3H3iYvdLCtgcNioezAeCINsD1rBeI8o+UVC8r39eyT6NJ55YXT/FEJO4D/k2XXsnZb1rqb5EhOE/h+n7tjIlQIGj6zps9icuqRPDT77mBksDxfLwcdJ/VKdE/nReVeAizjITWFlvQaaoZDqgcQP2ss1/SltCmNJCV+j1eK8ziL+AcYeZJCRk0I0stIINmA6QSlUAkOXnvoHw4Pa1AETy98CUzCv5Xrr1qDrywnjwTuuc2iFhSPEQxr5ZKigYLrXFF25cAgzVvu8VHgMgk28xC5i78RR0eQC3vTBjGsOS1AYt6QlLTMQR1UM5F5vwvX8F/1WhQj75OKFnC8Q5wFql0UZP8bxYynlNKzfmaIevG/qqtl476fim7EjShGhv5bY2wZTlAD1ICGPFfxyig/oCPzysgIeX3NbDKXg93op8KJs/3bcPjfTR+reO+dgYPlqUOb3Nnr9aEegkDA38txQRuYJCr2JbhkNwPGYNOOuzgC5oPULscp39f+2Q7gRwPqf8kV/Q4C5I=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
